### ISSUE TITLE
enhancement: Improving railway configuration of karma gap backend

### ISSUE THREAD

**Issue by FrancoAguzzi** [blockful-io/trustful-karma-gap-backend#8]
@RafaDSan can you add a description to this issue based on the feedbacks you received and want to implement?

**Comment by RafaDSan** [comment]
- [x] Add the output of the task in this issue comment section
- [x] Low down the resource limits of the server
- [ ] Create a documentation explaining each field of the database
- [ ] Add README

**Comment by RafaDSan** [comment]
Task output:

API endpoint on railway: https://trustful-karma-gap-backend-staging.up.railway.app/

![Image](https://github.com/user-attachments/assets/2501725e-92d1-468a-ab1f-32019f62d479)
